name: SweetP Productions Blog
title: Privacy Tips 
description: Useful guides and helpful tutorials 
meta_description: "Your Privacy is your business"
permalink: /:categories/:title/

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://sweetpproductions.com/blog'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://sweetpproductions.com/blog'
author:         'SweetP Productions'
